- Numpy Array Creation
- Shape
- indexing
- more creation methods: arange, linespace, ones, zeros, eye, diag
- random numbers: np.random.rand
- reshape: -1 for unknown
- data types: b,i,u,f,c,m,M,O,S,u,V
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort

In [1]:
import numpy as np
print(np.version.version)

1.26.3


In [10]:
l1 = [1,2,3,4]
l2 = [[1,2,3],[4,5,6]]
l3 = [[[1,2],[3,4]],[[5,6],[7,8]],[[50,60],[70,80]]]

In [11]:
print(l1[3],l2[1][0],l3[0][1][1])

4 4 4


In [12]:
na = np.array(l3)
print(na.shape,type(na),na.ndim)

(3, 2, 2) <class 'numpy.ndarray'> 3


In [13]:
na[0,1,1]

4

In [14]:
for i in range(na.shape[0]):
    for j in range(na.shape[1]):
        for k in range(na.shape[2]):
            print(na[i,j,k])

1
2
3
4
5
6
7
8
50
60
70
80


In [15]:
for ele in np.nditer(na):
    print(ele)

1
2
3
4
5
6
7
8
50
60
70
80


In [16]:
for ind,ele in np.ndenumerate(na):
    print(ind,ele)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
(2, 0, 0) 50
(2, 0, 1) 60
(2, 1, 0) 70
(2, 1, 1) 80


In [38]:
np.arange(1,10,2,dtype='f8')

array([1., 3., 5., 7., 9.])

In [22]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [32]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:
na.dtype

dtype('int32')

In [39]:
np.random.rand(2,5)

array([[0.81775859, 0.41828965, 0.04062991, 0.15706581, 0.65765723],
       [0.49614659, 0.15477213, 0.30162062, 0.19211188, 0.55783898]])

In [66]:
na = np.arange(1,21)

In [67]:
na = na.reshape((5,4))
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [50]:
na.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [68]:
a = na[:2,2:].copy()

In [69]:
a

array([[3, 4],
       [7, 8]])

In [70]:
np.shares_memory(a,na)

False

In [71]:
a[0,0]=30
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [72]:
a

array([[30,  4],
       [ 7,  8]])

In [75]:
na[:2,2:] = np.array([[10,20],[30,40]])

In [76]:
na

array([[ 1,  2, 10, 20],
       [ 5,  6, 30, 40],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [77]:
a

array([[30,  4],
       [ 7,  8]])

In [90]:
b = np.array([[10,20],[30,40]])

In [91]:
b+a

array([[40, 24],
       [37, 48]])

In [84]:
b

array([[10, 20],
       [30, 40]])

In [96]:
a[a>7]

array([30,  8])

In [103]:
na = np.arange(1,21).reshape((5,4))
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [105]:
na[[1,3,0],[2,3,3]]

array([ 7, 16,  4])

In [106]:
na = np.arange(1,21)

In [107]:
na[[6,3,8,1]]

array([7, 4, 9, 2])

In [108]:
np.where(na%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int64),)

In [117]:
na = np.arange(1,13).reshape((2,3,2))
na

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [125]:
np.sum(na,axis=-3)

array([[ 8, 10],
       [12, 14],
       [16, 18]])