pip install pandas \
pip install --upgrade pandas

In [1]:
import pandas as pd
import numpy as np
print(pd.__version__)

2.2.0


In [12]:
psa = pd.Series({'A':10,'B':20,'C':30},index=['A','B'])
print(psa)
psa.iloc[0] = 100
print(psa.iloc[0],psa.loc['A'])

A    10
B    20
dtype: int64
100 100


- Pandas DataFrame --> use various ways to initialize it(dtype,columns,index)
- shape
- head
- tail
- columns
- to_csv (index = false)
- read_csv
-  drop(columns=[])
-  describe()
-  info()
-  iloc
-  loc
-  Access Particular Columns
-  indexing and slicing --> multirow and col
-  columns.get_loc
-  unique
-  sort_values(by,ascending)
-  convert to numpy array --> values

In [27]:
d = {
    "MarksA" : np.random.randint(1,100,5),
    "MarksB" : np.random.randint(50,100,5),
    "MarksC" : np.random.randint(50,90,5) }

In [49]:
na = np.random.randint(1,100,(5,3))
df = pd.DataFrame(na,index=[10,20,30,40,50]
                  ,columns=["Phy","Chem","Maths"])

In [44]:
print(df)
print(type(df),type(d))

    Phy  Chem  Maths
10   92    83     56
20   38    85     14
30   27    88     68
40   78    91     25
50    5    54     75
<class 'pandas.core.frame.DataFrame'> <class 'dict'>


In [45]:
df

Phy  Chem  Maths
10   92    83     56
20   38    85     14
30   27    88     68
40   78    91     25
50    5    54     75

In [46]:
df.shape

(5, 3)

In [49]:
df.head(n=3)

Phy  Chem  Maths
10   92    83     56
20   38    85     14
30   27    88     68

In [52]:
df.tail(n=3)

Phy  Chem  Maths
30   27    88     68
40   78    91     25
50    5    54     75

In [53]:
df.columns

Index(['Phy', 'Chem', 'Maths'], dtype='object')

In [72]:
df.to_csv("Marks.csv",index=False)

In [76]:
df = pd.read_csv("Marks.csv",names=['a','b','c'],skiprows=1)

In [67]:
df = df.drop(columns = ["Unnamed: 0"])

In [77]:
df

a   b   c
0  92  83  56
1  38  85  14
2  27  88  68
3  78  91  25
4   5  54  75

In [70]:
df.describe()

Phy       Chem      Maths
count   5.000000   5.000000   5.000000
mean   48.000000  80.200000  47.600000
std    36.145539  14.956604  26.819769
min     5.000000  54.000000  14.000000
25%    27.000000  83.000000  25.000000
50%    38.000000  85.000000  56.000000
75%    78.000000  88.000000  68.000000
max    92.000000  91.000000  75.000000

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Phy     5 non-null      int64
 1   Chem    5 non-null      int64
 2   Maths   5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes


In [88]:
df

Phy  Chem  Maths
10   18    69     33
20   85    30     85
30   28    42     71
40   83    30     30
50   60    68     15

In [92]:
df[["Phy","Chem"]].loc[10:30]

Phy  Chem
10   18    69
20   85    30
30   28    42

In [93]:
df["Phy"].describe()

count     5.000000
mean     54.800000
std      30.849635
min      18.000000
25%      28.000000
50%      60.000000
75%      83.000000
max      85.000000
Name: Phy, dtype: float64

In [17]:
df.loc[:,["Phy","Maths"]]

Phy  Maths
10   81      4
20   54     73
30   66      5
40   19     88
50   53     49

In [18]:
df[["Phy","Maths"]]

Phy  Maths
10   81      4
20   54     73
30   66      5
40   19     88
50   53     49

In [21]:
df.iloc[[True,False,True,False,True]]

Phy  Chem  Maths
10   81    30      4
30   66    33      5
50   53    75     49

In [33]:
df[df['Phy']>=50].head(n=2)

Phy  Chem  Maths
10   81    30      4
20   54    83     73

In [37]:
df.columns.get_loc('Maths')

2

In [40]:
na = np.array([[10,20,10,30,10],[100,100,100,3,10]]).T
df = pd.DataFrame(na)
df

0    1
0  10  100
1  20  100
2  10  100
3  30    3
4  10   10

In [45]:
pd.unique(df[0])

array([10, 20, 30])

In [47]:
df[0].unique()

array([10, 20, 30])

In [50]:
df

Phy  Chem  Maths
10   36    75     76
20   63    57      1
30   12    41     14
40   34    68     13
50   52    90     18

In [59]:
df.sort_values(by=['Phy','Chem'],ascending=False)

Phy  Chem  Maths
50   63    90     18
20   63    57      1
10   36    75     76
40   34    68     13
30   12    41     14

In [61]:
df.loc[50,'Phy']=63

In [62]:
df

Phy  Chem  Maths
10   36    75     76
20   63    57      1
30   12    41     14
40   34    68     13
50   63    90     18

In [60]:
na = df.values
na

array([[36, 75, 76],
       [63, 57,  1],
       [12, 41, 14],
       [34, 68, 13],
       [63, 90, 18]])

In [64]:
df['Phy'].drop_duplicates()

10    36
20    63
30    12
40    34
Name: Phy, dtype: int32

In [67]:
for ele in df.itertuples():
    print(ele)

Pandas(Index=10, Phy=36, Chem=75, Maths=76)
Pandas(Index=20, Phy=63, Chem=57, Maths=1)
Pandas(Index=30, Phy=12, Chem=41, Maths=14)
Pandas(Index=40, Phy=34, Chem=68, Maths=13)
Pandas(Index=50, Phy=63, Chem=90, Maths=18)


- getdummies 
- groupby --> column name, various functions on grp, iterate
- pivot --> summarize and aggregate data,Grouper
- concat--> give as list, ignore_index,join
- merge--> on,how
- dropna
- fillna
- interpolate
- pip install matplotlib

In [4]:
na = np.array(list('abca'))
na

array(['a', 'b', 'c', 'a'], dtype='<U1')

In [6]:
pd.get_dummies(na,dtype='i8')

a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0

In [7]:
df = pd.read_csv('weather_data_cities.csv')

In [8]:
df

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [11]:
gdf = df.groupby('city')

In [12]:
for city,cdf in gdf:
    print(city)
    print(cdf)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy


In [13]:
gdf.describe()

temperature                                                   \
               count   mean       std   min    25%   50%    75%   max   
city                                                                    
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0   
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0   
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0   

         windspeed                                                 
             count   mean       std  min   25%   50%    75%   max  
city                                                               
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0  
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0  
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [16]:
gdf.mean(True)

temperature  windspeed
city                            
mumbai          88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [17]:
gdf.get_group('mumbai')

day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [20]:
df.pivot(index='city',columns='day')

temperature                            windspeed                    \
day         1/1/2017 1/2/2017 1/3/2017 1/4/2017  1/1/2017 1/2/2017 1/3/2017   
city                                                                          
mumbai            90       85       87       92         5       12       15   
new york          32       36       28       33         6        7       12   
paris             45       50       54       42        20       13        8   

                     event                             
day      1/4/2017 1/1/2017 1/2/2017 1/3/2017 1/4/2017  
city                                                   
mumbai          5    Sunny      Fog      Fog     Rain  
new york        7     Rain    Sunny     Snow    Sunny  
paris          10    Sunny   Cloudy   Cloudy   Cloudy

In [ ]:
pd.pivot_table()

In [24]:
df1 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['a','b','c'])
df1

a  b  c
0  1  2  3
1  4  5  6

In [34]:
df2 = pd.DataFrame([[10,2,30],[40,50,60]],columns=['a','b','d'])
df2

a   b   d
0  10   2  30
1  40  50  60

In [29]:
df3 = pd.concat([df1,df2],join='inner',ignore_index=True)
df3

a   b
0   1   2
1   4   5
2  10  20
3  40  50

In [32]:
pd.concat([df1,df2],axis=1,ignore_index=True)

0  1  2   3   4   5
0  1  2  3  10  20  30
1  4  5  6  40  50  60

In [39]:
pd.merge(df1,df2,on='b',how='outer')

a_x   b    c   a_y     d
0  1.0   2  3.0  10.0  30.0
1  4.0   5  6.0   NaN   NaN
2  NaN  50  NaN  40.0  60.0