- Numpy Array Creation
- Shape
- indexing
- more creation methods: arange, linespace, ones, zeros, eye, diag
- random numbers: np.random.rand
- reshape: -1 for unknown
- data types: b,i,u,f,c,m,M,O,S,u,V
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort

In [1]:
import numpy as np

In [6]:
print(np.version.version)

1.26.3


In [42]:
l1 = [1,2,3,4]
l2 = [[1,2],[3,4]]
l21 = [[1,2,3],[4,5,6]]
l3 = [[[1,2],[3,4],[8,9]],[[5,6],[7,8],[1,2]]]
l31 = [[[1],[3],[8]],[[5],[7],[1]]]
na = np.array(l3)

In [43]:
print(na,type(na),na.ndim)

[[[1 2]
  [3 4]
  [8 9]]

 [[5 6]
  [7 8]
  [1 2]]] <class 'numpy.ndarray'> 3


In [44]:
na.shape

(2, 3, 2)

In [45]:
na[0]

array([[1, 2],
       [3, 4],
       [8, 9]])

In [47]:
for i in range(na.shape[0]):
    for j in range(na.shape[1]):
        for k in range(na.shape[2]):
            print(na[i,j,k],end=" ")

1 2 3 4 8 9 5 6 7 8 1 2 

In [48]:
for ele in np.nditer(na):
    print(ele,end = " ")

1 2 3 4 8 9 5 6 7 8 1 2 

In [49]:
for ind,ele in np.ndenumerate(na):
    print(ind,ele)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 2, 0) 8
(0, 2, 1) 9
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
(1, 2, 0) 1
(1, 2, 1) 2


In [50]:
na.dtype

dtype('int32')

In [56]:
np.arange(1,10,2,dtype= 'f8')

array([1., 3., 5., 7., 9.])

In [59]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [63]:
np.ones((2,5),dtype='i')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [64]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [67]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [68]:
np.random.rand(2,5)

array([[0.23869568, 0.74194115, 0.37852005, 0.84664679, 0.97202727],
       [0.22514422, 0.72564426, 0.90640625, 0.60076222, 0.40024863]])

In [97]:
na = np.arange(1,21)

In [98]:
na= na.reshape((5,-1))
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [99]:
a = na[0:2,2:4].copy()
a[0,0] = 10
print(a)
print(na)

[[10  4]
 [ 7  8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [95]:
np.shares_memory(na,b)

False

In [100]:
b = np.array([[10,20],[30,40]])

In [103]:
b-10,np.add(b,10)

(array([[ 0, 10],
        [20, 30]]),
 array([[20, 30],
        [40, 50]]))

In [104]:
b**2

array([[ 100,  400],
       [ 900, 1600]])

In [105]:
a+b

array([[20, 24],
       [37, 48]])

In [106]:
a

array([[10,  4],
       [ 7,  8]])

In [108]:
a[a>7]

array([10,  8])

In [112]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [113]:
np.where(a%4==0)

(array([ 3,  7, 11, 15, 19], dtype=int64),)

In [120]:
na = np.arange(1,13).reshape((2,3,2))
na

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [123]:
np.sum(na,axis=2)

array([[ 3,  7, 11],
       [15, 19, 23]])