In [1]:
#!pip install pandas
import pandas as pd
import numpy as np
print(pd.__version__)

2.2.0


- Pandas DataFrame --> use various ways to initialize it(dtype,columns,index)
- shape
- head
- tail
- columns
- to_csv (index = false)
- read_csv
-  drop(columns=[])
-  describe()
-  info()
-  iloc
-  loc
-  Access Particular Columns
-  indexing and slicing --> multirow and col
-  Filter
-  columns.get_loc
-  unique
-  sort_values(by,ascending)
-  convert to numpy array --> values

In [20]:
psa = pd.Series({'A':10,'B':20,'C':30})
print(psa)
psa.loc['A'] = 100
print(psa.loc['A'],psa.iloc[0])

A    10
B    20
C    30
dtype: int64
100 100


In [8]:
np.random.randint(1,100,(2,3))

array([[82, 75, 89],
       [78, 91,  8]])

In [9]:
d = {
    "MarksA":np.random.randint(1,100,5),
    "MarksB":np.random.randint(50,100,5),
    "MarksC":np.random.randint(70,90,5)}
d

{'MarksA': array([74, 96,  8,  6,  9]),
 'MarksB': array([69, 55, 71, 60, 90]),
 'MarksC': array([71, 78, 76, 71, 82])}

In [17]:
df = pd.DataFrame(d,columns = ["MarksA","MarksC","Phy"])
df

MarksA  MarksC  Phy
0      74      71  NaN
1      96      78  NaN
2       8      76  NaN
3       6      71  NaN
4       9      82  NaN

In [14]:
# pd.DataFrame

In [2]:
na = np.random.randint(1,100,(5,3))
df = pd.DataFrame(na,columns=["Phy","Chem","Maths"]
                  ,index =[10,20,30,40,50])
df

Phy  Chem  Maths
10   90    71     38
20   78    77     13
30   88    47      1
40   60    81     54
50   13    99      6

In [38]:
df.shape

(5, 3)

In [39]:
df.head(n=3)

Phy  Chem  Maths
10   16    68     45
20   22    65     59
30   77    36     45

In [40]:
df.tail(n=3)

Phy  Chem  Maths
30   77    36     45
40   30    58     51
50   12    93      6

In [41]:
df.columns

Index(['Phy', 'Chem', 'Maths'], dtype='object')

In [42]:
df.to_csv("Marks.csv")

In [50]:
df = pd.read_csv("Marks.csv",names=['a','b','c','d']
                 ,skiprows=1)
df

a   b   c   d
0  10  16  68  45
1  20  22  65  59
2  30  77  36  45
3  40  30  58  51
4  50  12  93   6

In [51]:
df.drop(columns=["a"],inplace=True)
df

b   c   d
0  16  68  45
1  22  65  59
2  77  36  45
3  30  58  51
4  12  93   6

In [68]:
df

Phy  Chem  Maths
10   69    76     54
20   10    66     25
30   61    69      8
40    8    31     21
50    2    81     82

In [54]:
df.describe()

Phy       Chem      Maths
count   5.000000   5.000000   5.000000
mean   30.000000  64.600000  38.000000
std    32.210247  19.679939  29.790938
min     2.000000  31.000000   8.000000
25%     8.000000  66.000000  21.000000
50%    10.000000  69.000000  25.000000
75%    61.000000  76.000000  54.000000
max    69.000000  81.000000  82.000000

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 10 to 50
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Phy     5 non-null      int32
 1   Chem    5 non-null      int32
 2   Maths   5 non-null      int32
dtypes: int32(3)
memory usage: 100.0 bytes


In [73]:
df[["Phy","Chem"]].iloc[[True,False,True,False,True]]

Phy  Chem
10   69    76
30   61    69
50    2    81

In [77]:
df.loc[10:30]

Phy  Chem  Maths
10   69    76     54
20   10    66     25
30   61    69      8

In [10]:
df.iloc[0:3,0:2].describe()

Phy       Chem
count   3.000000   3.000000
mean   85.333333  65.000000
std     6.429101  15.874508
min    78.000000  47.000000
25%    83.000000  59.000000
50%    88.000000  71.000000
75%    89.000000  74.000000
max    90.000000  77.000000

In [12]:
df['Phy'].describe()

count     5.000000
mean     65.800000
std      31.815091
min      13.000000
25%      60.000000
50%      78.000000
75%      88.000000
max      90.000000
Name: Phy, dtype: float64

In [19]:
df[['Phy','Chem']][df['Phy'] >= 50]

Phy  Chem
10   90    71
20   78    77
30   88    47
40   60    81

In [29]:
df[df['Phy'] >= 50]

Phy  Chem  Maths
10   90    71     38
20   78    77     13
30   88    47      1
40   60    81     54

In [31]:
df.columns.get_loc('Phy')

0

In [34]:
na = np.array([[10,20,10,30,10],[100,30,100,10,40]]).T
df = pd.DataFrame(na)

In [35]:
df

0    1
0  10  100
1  20   30
2  10  100
3  30   10
4  10   40

In [39]:
pd.unique(df[0])

array([10, 20, 30])

In [42]:
df[1].unique()

array([100,  30,  10,  40])

In [46]:
df.sort_values(by = [0,1],ascending=True)

0    1
4  10   40
0  10  100
2  10  100
1  20   30
3  30   10

In [47]:
na = df.values
print(na,type(na))

[[ 10 100]
 [ 20  30]
 [ 10 100]
 [ 30  10]
 [ 10  40]] <class 'numpy.ndarray'>


- getdummies 
- groupby --> column name, various functions on grp, iterate
- pivot --> summarize and aggregate data,Grouper
- concat--> give as list, ignore_index,join
- merge--> on,how
- dropna
- fillna
- interpolate
- pip install matplotlib

In [2]:
na = np.array(list('abca'))


array(['a', 'b', 'c', 'a'], dtype='<U1')

In [5]:
df = pd.get_dummies(na,dtype='i8')
df

a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0

In [7]:
df = pd.read_csv('weather_data_cities.csv')

In [8]:
gdf = df.groupby('city')

In [10]:
for city,cdf in gdf:
    print(city)
    print(cdf)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy


In [12]:
gdf.describe()

temperature                                                   \
               count   mean       std   min    25%   50%    75%   max   
city                                                                    
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0   
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0   
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0   

         windspeed                                                 
             count   mean       std  min   25%   50%    75%   max  
city                                                               
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0  
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0  
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [15]:
gdf.mean(True)

temperature  windspeed
city                            
mumbai          88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [16]:
gdf.get_group('mumbai')

day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [17]:
df

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [20]:
df.pivot(index='city',columns='day')

temperature                            windspeed                    \
day         1/1/2017 1/2/2017 1/3/2017 1/4/2017  1/1/2017 1/2/2017 1/3/2017   
city                                                                          
mumbai            90       85       87       92         5       12       15   
new york          32       36       28       33         6        7       12   
paris             45       50       54       42        20       13        8   

                     event                             
day      1/4/2017 1/1/2017 1/2/2017 1/3/2017 1/4/2017  
city                                                   
mumbai          5    Sunny      Fog      Fog     Rain  
new york        7     Rain    Sunny     Snow    Sunny  
paris          10    Sunny   Cloudy   Cloudy   Cloudy

In [21]:
df.pivot(columns='city',index='day')

temperature                windspeed                 event           \
city          mumbai new york paris    mumbai new york paris mumbai new york   
day                                                                            
1/1/2017          90       32    45         5        6    20  Sunny     Rain   
1/2/2017          85       36    50        12        7    13    Fog    Sunny   
1/3/2017          87       28    54        15       12     8    Fog     Snow   
1/4/2017          92       33    42         5        7    10   Rain    Sunny   

                  
city       paris  
day               
1/1/2017   Sunny  
1/2/2017  Cloudy  
1/3/2017  Cloudy  
1/4/2017  Cloudy

In [22]:
df.pivot(columns='city',index='temperature')

day                     windspeed                 event  \
city           mumbai  new york     paris    mumbai new york paris mumbai   
temperature                                                                 
28                NaN  1/3/2017       NaN       NaN     12.0   NaN    NaN   
32                NaN  1/1/2017       NaN       NaN      6.0   NaN    NaN   
33                NaN  1/4/2017       NaN       NaN      7.0   NaN    NaN   
36                NaN  1/2/2017       NaN       NaN      7.0   NaN    NaN   
42                NaN       NaN  1/4/2017       NaN      NaN  10.0    NaN   
45                NaN       NaN  1/1/2017       NaN      NaN  20.0    NaN   
50                NaN       NaN  1/2/2017       NaN      NaN  13.0    NaN   
54                NaN       NaN  1/3/2017       NaN      NaN   8.0    NaN   
85           1/2/2017       NaN       NaN      12.0      NaN   NaN    Fog   
87           1/3/2017       NaN       NaN      15.0      NaN   NaN    Fog   
90           1/1/2017       NaN       NaN       5.0      NaN   NaN  Sunny   
92           1/4/2017       NaN       NaN       5.0      NaN   NaN   Rain   

                              
city        new york   paris  
temperature                   
28              Snow     NaN  
32              Rain     NaN  
33             Sunny     NaN  
36             Sunny     NaN  
42               NaN  Cloudy  
45               NaN   Sunny  
50               NaN  Cloudy  
54               NaN  Cloudy  
85               NaN     NaN  
87               NaN     NaN  
90               NaN     NaN  
92               NaN     NaN

In [39]:
df1 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['a','b','c'])
df1

a  b  c
0  1  2  3
1  4  5  6

In [40]:
df2 = pd.DataFrame([[10,2,30],[40,50,60]],columns=['a','b','d'])
df2

a   b   d
0  10   2  30
1  40  50  60

In [30]:
df3 = pd.concat([df1,df2],ignore_index=True,join='inner')
df3

a   b
0   1   2
1   4   5
2  10  20
3  40  50

In [33]:
df3 = pd.concat([df1,df2],axis=1,ignore_index=True)
df3

0  1  2   3   4   5
0  1  2  3  10  20  30
1  4  5  6  40  50  60

In [44]:
pd.merge(left=df1,right=df2,how='outer',on='b')

a_x   b    c   a_y     d
0  1.0   2  3.0  10.0  30.0
1  4.0   5  6.0   NaN   NaN
2  NaN  50  NaN  40.0  60.0