- Numpy Array Creation
- Shape
- indexing
- more creation methods: arange, linespace, ones, zeros, eye, diag
- random numbers: np.random.rand
- reshape: -1 for unknown
- data types: b,i,u,f,c,m,M,O,S,u,V
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort

In [1]:
import numpy as np

In [2]:
np.version.version

'1.26.3'

In [75]:
l1 = [1,2,3,4]
l2 = [[1,2],[3,4]]
l21 = [[1,2,3],[4,5,6]]
l3 = [[[1,2],[3,4],[8,9]],[[5,6],[7,8],[1,2]]]
l31 = [[[1],[3],[8]],[[5],[7],[1]]]
na = np.array(l21)

In [25]:
print(na,type(na),na.ndim)

[[[1 2]
  [3 4]
  [8 9]]

 [[5 6]
  [7 8]
  [1 2]]] <class 'numpy.ndarray'> 3


In [26]:
na.shape

(2, 3, 2)

In [29]:
na[0,1,1]

4

In [31]:
for i in range(na.shape[0]):
    for j in range(na.shape[1]):
        for k in range(na.shape[2]):
            print(na[i,j,k],end=" ")

1 2 3 4 8 9 5 6 7 8 1 2 

In [32]:
for ele in np.nditer(na):
    print(ele,end=" ")

1 2 3 4 8 9 5 6 7 8 1 2 

In [33]:
for ind, ele in np.ndenumerate(na):
    print(ind,ele)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 2, 0) 8
(0, 2, 1) 9
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
(1, 2, 0) 1
(1, 2, 1) 2


In [34]:
na.dtype

dtype('int32')

In [40]:
np.arange(1,10,2,dtype='f8')

array([1., 3., 5., 7., 9.])

In [44]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [48]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [52]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [55]:
np.random.rand(2,5)

array([[0.1988324 , 0.11533692, 0.58696494, 0.13348656, 0.81183178],
       [0.82059702, 0.01416009, 0.38645444, 0.29987922, 0.08475357]])

In [59]:
for i in range(10):
    print(np.random.randint(1,10),end = " ")

9 6 3 1 1 9 3 7 2 5 

In [62]:
np.random.random((2,5))

array([[0.07505535, 0.80824366, 0.62620062, 0.10423002, 0.15974991],
       [0.82573446, 0.57531151, 0.66006884, 0.28099712, 0.44149356]])

In [77]:
na = np.arange(1,17)

In [78]:
na = na.reshape((4,4))

In [74]:
na.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [82]:
na2 = np.array([[10,20],[30,40]])

In [83]:
na[0:2,2:4] = na2

In [84]:
na

array([[ 1,  2, 10, 20],
       [ 5,  6, 30, 40],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [87]:
b = na[0:2,2:4].copy()

In [88]:
np.shares_memory(na,b)

False

In [99]:
na[0:2,2:4]+b

array([[20, 40],
       [60, 80]])

In [101]:
np.add(na[0:2,2:4],b)

array([[20, 40],
       [60, 80]])

In [102]:
na = np.arange(1,21)

In [107]:
f = na%2==0

In [108]:
na[f]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [109]:
np.where(na%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int64),)

In [116]:
na3 = np.arange(1,13).reshape((2,3,2))
na3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [120]:
np.sum(na3,axis=2)

array([[ 3,  7, 11],
       [15, 19, 23]])