pip install pandas \
pip install --upgrade pandas

In [1]:
import pandas as pd
import numpy as np
print(pd.__version__)

2.2.0


- Pandas Series
- Pandas DataFrame --> use various ways to initialize it(dtype,columns,index)
- shape
- head
- tail
- columns
- to_csv (index = false)
- read_csv
-  drop(columns=[])
-  describe()
-  info()
-  iloc
-  loc
-  Access Particular Columns
-  indexing and slicing --> multirow and col
-  columns.get_loc
-  unique
-  sort_values(by,ascending)
-  convert to numpy array --> values

In [46]:
l = np.array([10,20,30,40])
d = {'A':10,'B':20,'C':30,'D':40}

In [51]:
# psa = pd.Series(l,dtype=np.int8)
# psa = pd.Series(l,index=['a','b','c','d'])
psa = pd.Series(d,index=['A','C','E'])

In [52]:
psa

A    10.0
C    30.0
E     NaN
dtype: float64

In [37]:
psa.iloc[0],psa.loc['b']

(10, 20)

In [38]:
psa.iloc[0] = 100

In [54]:
np.random.randint(1,100,5)

array([91,  8, 41, 59,  5])

In [68]:
d = {
    "MarksA" : np.random.randint(1,100,5),
    "MarksB" : np.random.randint(50,100,5),
    "MarksC" : np.random.randint(70,90,5)}

In [69]:
print(d)
print(type(d))

{'MarksA': array([82, 77, 28, 15, 24]), 'MarksB': array([83, 79, 63, 94, 52]), 'MarksC': array([88, 73, 74, 76, 72])}
<class 'dict'>


In [71]:
df = pd.DataFrame(d,index=['a','b','c','d','e'])
                  #,columns=["MarksA","MarksC","Phy"])
df

MarksA  MarksB  MarksC
a      82      83      88
b      77      79      73
c      28      63      74
d      15      94      76
e      24      52      72

In [79]:
na = np.random.randint(1,100,(6,3))

In [81]:
df = pd.DataFrame(na,columns=["Phy","Chem","Maths"]
                 ,index = [10,20,30,40,50,60])
df

Phy  Chem  Maths
10   24    67     63
20   82    48      9
30   36    77     80
40   44    12     11
50   46    84     71
60   37    31     51

In [83]:
df.head(n=3)

Phy  Chem  Maths
10   24    67     63
20   82    48      9
30   36    77     80

In [85]:
df.tail(n=3)

Phy  Chem  Maths
40   44    12     11
50   46    84     71
60   37    31     51

In [86]:
df.shape

(6, 3)

In [87]:
df.columns

Index(['Phy', 'Chem', 'Maths'], dtype='object')

In [92]:
df.to_csv("Marks.csv")

In [98]:
df = pd.read_csv("Marks.csv",names=["A","B","C","D"]
                 ,skiprows = 1)
df

A   B   C   D
0  0  24  67  63
1  1  82  48   9
2  2  36  77  80
3  3  44  12  11
4  4  46  84  71
5  5  37  31  51

In [96]:
df = df.drop(columns=["Unnamed: 0"])
df

Phy  Chem  Maths
0   24    67     63
1   82    48      9
2   36    77     80
3   44    12     11
4   46    84     71
5   37    31     51

In [68]:
df

Phy  Chem  Maths
10   69    76     54
20   10    66     25
30   61    69      8
40    8    31     21
50    2    81     82

In [54]:
df.describe()

Phy       Chem      Maths
count   5.000000   5.000000   5.000000
mean   30.000000  64.600000  38.000000
std    32.210247  19.679939  29.790938
min     2.000000  31.000000   8.000000
25%     8.000000  66.000000  21.000000
50%    10.000000  69.000000  25.000000
75%    61.000000  76.000000  54.000000
max    69.000000  81.000000  82.000000

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 10 to 50
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Phy     5 non-null      int32
 1   Chem    5 non-null      int32
 2   Maths   5 non-null      int32
dtypes: int32(3)
memory usage: 100.0 bytes


In [73]:
df[["Phy","Chem"]].iloc[[True,False,True,False,True]]

Phy  Chem
10   69    76
30   61    69
50    2    81

In [77]:
df.loc[10:30]

Phy  Chem  Maths
10   69    76     54
20   10    66     25
30   61    69      8

In [10]:
df.iloc[0:3,0:2].describe()

Phy       Chem
count   3.000000   3.000000
mean   85.333333  65.000000
std     6.429101  15.874508
min    78.000000  47.000000
25%    83.000000  59.000000
50%    88.000000  71.000000
75%    89.000000  74.000000
max    90.000000  77.000000

In [12]:
df['Phy'].describe()

count     5.000000
mean     65.800000
std      31.815091
min      13.000000
25%      60.000000
50%      78.000000
75%      88.000000
max      90.000000
Name: Phy, dtype: float64

In [19]:
df[['Phy','Chem']][df['Phy'] >= 50]

Phy  Chem
10   90    71
20   78    77
30   88    47
40   60    81

In [29]:
df[df['Phy'] >= 50]

Phy  Chem  Maths
10   90    71     38
20   78    77     13
30   88    47      1
40   60    81     54

In [31]:
df.columns.get_loc('Phy')

0

In [34]:
na = np.array([[10,20,10,30,10],[100,30,100,10,40]]).T
df = pd.DataFrame(na)

In [35]:
df

0    1
0  10  100
1  20   30
2  10  100
3  30   10
4  10   40

In [39]:
pd.unique(df[0])

array([10, 20, 30])

In [42]:
df[1].unique()

array([100,  30,  10,  40])

In [46]:
df.sort_values(by = [0,1],ascending=True)

0    1
4  10   40
0  10  100
2  10  100
1  20   30
3  30   10

In [47]:
na = df.values
print(na,type(na))

[[ 10 100]
 [ 20  30]
 [ 10 100]
 [ 30  10]
 [ 10  40]] <class 'numpy.ndarray'>


In [ ]:
df.drop_duplicates()

- getdummies 
- groupby --> column name, various functions on grp, iterate
- pivot --> summarize and aggregate data,Grouper
- concat--> give as list, ignore_index,join
- merge--> on,how
- dropna
- fillna
- interpolate
- pip install matplotlib

In [3]:
na = np.array(list('abca'))
na

array(['a', 'b', 'c', 'a'], dtype='<U1')

In [6]:
df = pd.get_dummies(na,dtype='i1')
df

a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0

In [8]:
df = pd.read_csv('weather_data_cities.csv')
df

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [9]:
gdf = df.groupby('city')

In [11]:
for city,cdf in gdf:
    print(city)
    print(cdf)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy


In [14]:
df.pivot(index='city',columns='day')

temperature                            windspeed                    \
day         1/1/2017 1/2/2017 1/3/2017 1/4/2017  1/1/2017 1/2/2017 1/3/2017   
city                                                                          
mumbai            90       85       87       92         5       12       15   
new york          32       36       28       33         6        7       12   
paris             45       50       54       42        20       13        8   

                     event                             
day      1/4/2017 1/1/2017 1/2/2017 1/3/2017 1/4/2017  
city                                                   
mumbai          5    Sunny      Fog      Fog     Rain  
new york        7     Rain    Sunny     Snow    Sunny  
paris          10    Sunny   Cloudy   Cloudy   Cloudy

In [17]:
df1 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['a','b','c'])
df1

a  b  c
0  1  2  3
1  4  5  6

In [18]:
df2 = pd.DataFrame([[10,2,30],[40,50,60]],columns=['a','b','d'])
df2

a   b   d
0  10   2  30
1  40  50  60

In [24]:
df3 = pd.concat([df1,df2],ignore_index=True,join='inner')
df3

a   b
0   1   2
1   4   5
2  10   2
3  40  50

In [23]:
df3 = pd.concat([df1,df2],axis=1,ignore_index=True)
df3

0  1  2   3   4   5
0  1  2  3  10   2  30
1  4  5  6  40  50  60

In [28]:
pd.merge(df1,df2,on='b',how='outer')

a_x   b    c   a_y     d
0  1.0   2  3.0  10.0  30.0
1  4.0   5  6.0   NaN   NaN
2  NaN  50  NaN  40.0  60.0

In [29]:
pd.merge?

Signature:
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning: