- Numpy Array Creation
- Shape
- indexing
- more creation methods: arange, linespace, ones, zeros, eye, diag
- random numbers: np.random.rand
- reshape: -1 for unknown
- data types: b,i,u,f,c,m,M,O,S,u,V
- slicing and assignment
- copy and view: share_memory
- operators(Element wise operations)
- shape mismatch
- fancy indexing also know as filter
- search: where uses fancy indexing
- Basic reductions: sum, min, max, any, all
- iteration: nditer, ndenumerate
- Join: concatenate, stack, hstack, vstack. Note: make a tuple of arays you want to join
- split: array_split, hsplit
- sort: np.sort

In [3]:
import numpy as np
print(np.version.version)

1.26.3


In [4]:
l1 = [1,2,3,4]
l2 = [[1,2,3],[4,5,6]]
l3 = [[[1,2],[3,4]],[[6,7],[8,9]]]

In [8]:
print(l1[1],l2[0][2],l3[0][1][1])

2 3 4


In [17]:
na = np.array(l3)
print(na,type(na),na.ndim)
na[0,1,1]

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]] <class 'numpy.ndarray'> 3


4

In [16]:
na.shape

(2, 2, 2)

In [19]:
for i in range(na.shape[0]):
    for j in range(na.shape[1]):
        for k in range(na.shape[2]):
            print(na[i,j,k],end = " ")

1 2 3 4 6 7 8 9 

In [20]:
for ele in np.nditer(na):
    print(ele,end = " ")

1 2 3 4 6 7 8 9 

In [21]:
for ind,ele in np.ndenumerate(na):
    print(ind,ele)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 6
(1, 0, 1) 7
(1, 1, 0) 8
(1, 1, 1) 9


In [22]:
na.dtype

dtype('int32')

In [27]:
np.arange(1,10,2,dtype='f8')

array([1., 3., 5., 7., 9.])

In [28]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
np.ones((2,5),dtype='i')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [39]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [43]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [45]:
np.random.rand(2,5)

array([[0.71006191, 0.22907736, 0.29656162, 0.13622149, 0.60802343],
       [0.03276063, 0.31754072, 0.06268233, 0.30027099, 0.54251898]])

In [72]:
na = np.arange(1,21)

In [73]:
na = na.reshape((5,4))
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [68]:
nb = np.array([[10,20],[30,40]])

In [69]:
na[0:2,2:4] = nb

In [70]:
na

array([[ 1,  2, 10, 20],
       [ 5,  6, 30, 40],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [76]:
b = na[0:2,2:4].copy()
print(b)

[[3 4]
 [7 8]]


In [77]:
np.shares_memory(na,b)

False

In [78]:
nb

array([[10, 20],
       [30, 40]])

In [79]:
b

array([[3, 4],
       [7, 8]])

In [83]:
nb <= 20

array([[ True,  True],
       [False, False]])

In [84]:
nb + b

array([[13, 24],
       [37, 48]])

In [85]:
na = np.arange(1,21)

In [87]:
na[na%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [88]:
np.where(na%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int64),)

In [103]:
na = np.arange(1,13)
na = na.reshape((2,3,2))

In [104]:
na

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [107]:
np.sum(na,axis=2)

array([[ 3,  7, 11],
       [15, 19, 23]])