pip install pandas \
pip install --upgrade pandas

In [1]:
import pandas as pd
import numpy as np
print(pd.__version__)

2.2.0


- Pandas Series
- Pandas DataFrame --> use various ways to initialize it(dtype,columns,index)
- shape
- head
- tail
- columns
- to_csv (index = false)
- read_csv
-  drop(columns=[])
-  describe()
-  info()
-  iloc
-  loc
-  Access Particular Columns
-  indexing and slicing --> multirow and col
-  columns.get_loc
-  unique
-  sort_values(by,ascending)
-  convert to numpy array --> values

In [14]:
l = [10,20,30,40]
d = {'a':10,'b':20,'c':30}
print(d,type(d))

{'a': 10, 'b': 20, 'c': 30} <class 'dict'>


In [18]:
# psa = pd.Series(l,index=['a','b','c','d'],dtype=np.int8)
psa = pd.Series(d,index=['a','c','d'])
psa

a    10.0
c    30.0
d     NaN
dtype: float64

In [22]:
psa.iloc[0],psa.loc['a']

(100.0, 100.0)

In [21]:
psa.iloc[0] = 100

In [26]:
# psa.iloc[0:2]
psa.loc['a':'c']

a    100.0
c     30.0
dtype: float64

In [30]:
np.random.randint(1,100,(2,2))

array([[47, 71],
       [61, 19]])

In [32]:
d = {
    "MarksA" : np.random.randint(1,100,6),
    "MarksB" : np.random.randint(50,100,6),
    "MarksC" : np.random.randint(70,90,6)
}

In [36]:
d,type(d)

({'MarksA': array([56, 55, 81, 98, 55, 96]),
  'MarksB': array([97, 59, 78, 89, 69, 67]),
  'MarksC': array([88, 88, 77, 85, 70, 76])},
 dict)

In [42]:
df = pd.DataFrame(d,index = [10,20,30,40,50,60]
                  ,columns=["MarksA","MarksC","Phy"])

In [43]:
df

MarksA  MarksC  Phy
10      56      88  NaN
20      55      88  NaN
30      81      77  NaN
40      98      85  NaN
50      55      70  NaN
60      96      76  NaN

In [39]:
type(df)

pandas.core.frame.DataFrame

In [59]:
na = np.random.randint(1,100,(6,3))
df = pd.DataFrame(na,columns=["Phy","Chem","Maths"]
                  ,index = [10,30,20,50,70,40])
df

Phy  Chem  Maths
10   41     3     81
30   37    34     89
20   51    41      4
50   47    48      4
70   77    42     34
40   89    71     28

In [52]:
df.head(n=3)

Phy  Chem  Maths
10   90    97     59
30   63    83     21
20   25    98     86

In [54]:
df.tail(n=3)

Phy  Chem  Maths
50   67    33     59
70   96    61     59
40   67    82     85

In [55]:
df.shape

(6, 3)

In [56]:
df.columns

Index(['Phy', 'Chem', 'Maths'], dtype='object')

In [61]:
df.to_csv("Marks.csv")

In [69]:
df = pd.read_csv("Marks.csv",names = ['a','b','c'],skiprows=1)

In [70]:
df

a   b   c
0  90  97  59
1  63  83  21
2  25  98  86
3  67  33  59
4  96  61  59
5  67  82  85

In [65]:
df = df.drop(columns=["Unnamed: 0"])

In [60]:
df

Phy  Chem  Maths
10   41     3     81
30   37    34     89
20   51    41      4
50   47    48      4
70   77    42     34
40   89    71     28

In [63]:
df.describe()

Phy       Chem      Maths
count   6.000000   6.000000   6.000000
mean   57.000000  39.833333  40.000000
std    21.052316  22.067321  37.024316
min    37.000000   3.000000   4.000000
25%    42.500000  35.750000  10.000000
50%    49.000000  41.500000  31.000000
75%    70.500000  46.500000  69.250000
max    89.000000  71.000000  89.000000

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 10 to 40
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Phy     6 non-null      int32
 1   Chem    6 non-null      int32
 2   Maths   6 non-null      int32
dtypes: int32(3)
memory usage: 120.0 bytes


In [72]:
df.iloc[[1,3,4],[2,0]]

Maths  Phy
30     89   37
50      4   47
70     34   77

In [74]:
df.iloc[0,1] = 100

In [75]:
df

Phy  Chem  Maths
10   41   100     81
30   37    34     89
20   51    41      4
50   47    48      4
70   77    42     34
40   89    71     28

In [78]:
df.loc[10:50,['Phy','Maths']]

Phy  Maths
10   41     81
30   37     89
20   51      4
50   47      4

In [79]:
df.loc[10:50,'Chem':'Maths']

Chem  Maths
10   100     81
30    34     89
20    41      4
50    48      4

In [80]:
df.iloc[:,0]

10    41
30    37
20    51
50    47
70    77
40    89
Name: Phy, dtype: int32

In [84]:
df[['Phy','Maths']].iloc[0:4]

Phy  Maths
10   41     81
30   37     89
20   51      4
50   47      4

In [85]:
df.iloc[0][0:2]

Phy      41
Chem    100
Name: 10, dtype: int32

In [86]:
df.iloc[[True,False,True,True,False,True]]

Phy  Chem  Maths
10   41   100     81
20   51    41      4
50   47    48      4
40   89    71     28

In [87]:
df.iloc[:,[True,False,True]]

Phy  Maths
10   41     81
30   37     89
20   51      4
50   47      4
70   77     34
40   89     28

In [92]:
df.loc[df['Phy'] >= 50]

Phy  Chem  Maths
20   51    41      4
70   77    42     34
40   89    71     28

In [93]:
df[df['Phy'] >= 50]

Phy  Chem  Maths
20   51    41      4
70   77    42     34
40   89    71     28

In [95]:
df.columns.get_loc('Phy')

0

In [100]:
na = np.array([[10,20,10,30,20,10],[100,20,100,10,10,40]]).T
df = pd.DataFrame(na)
df

0    1
0  10  100
1  20   20
2  10  100
3  30   10
4  20   10
5  10   40

In [103]:
pd.unique(df[0])

array([10, 20, 30])

In [104]:
df[1].unique()

array([100,  20,  10,  40])

In [108]:
df.sort_values(by=[0,1],ascending=True)

0    1
5  10   40
0  10  100
2  10  100
4  20   10
1  20   20
3  30   10

In [109]:
df.drop_duplicates()

0    1
0  10  100
1  20   20
3  30   10
4  20   10
5  10   40

In [110]:
na = df.values
print(na,type(na))

[[ 10 100]
 [ 20  20]
 [ 10 100]
 [ 30  10]
 [ 20  10]
 [ 10  40]] <class 'numpy.ndarray'>


- getdummies 
- groupby --> column name, various functions on grp, iterate
- pivot --> summarize and aggregate data,Grouper
- concat--> give as list, ignore_index,join
- merge--> on,how
- dropna
- fillna
- interpolate
- pip install matplotlib

In [2]:
na = np.array(list('abca'))
na

array(['a', 'b', 'c', 'a'], dtype='<U1')

In [5]:
pd.get_dummies(na,dtype='i1')

a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0

In [7]:
df = pd.read_csv('weather_data_cities.csv')
df

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [8]:
gdf = df.groupby('city')
gdf

In [9]:
for city,cdf in gdf:
    print(city)
    print(cdf)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy


In [10]:
gdf.describe()

temperature                                                   \
               count   mean       std   min    25%   50%    75%   max   
city                                                                    
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0   
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0   
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0   

         windspeed                                                 
             count   mean       std  min   25%   50%    75%   max  
city                                                               
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0  
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0  
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [13]:
gdf.mean(True)

temperature  windspeed
city                            
mumbai          88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [14]:
gdf.get_group('mumbai')

day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [15]:
df.pivot(index = 'day',columns='city')

temperature                windspeed                 event           \
city          mumbai new york paris    mumbai new york paris mumbai new york   
day                                                                            
1/1/2017          90       32    45         5        6    20  Sunny     Rain   
1/2/2017          85       36    50        12        7    13    Fog    Sunny   
1/3/2017          87       28    54        15       12     8    Fog     Snow   
1/4/2017          92       33    42         5        7    10   Rain    Sunny   

                  
city       paris  
day               
1/1/2017   Sunny  
1/2/2017  Cloudy  
1/3/2017  Cloudy  
1/4/2017  Cloudy

In [17]:
df.pivot(index = 'temperature',columns='city')

day                     windspeed                 event  \
city           mumbai  new york     paris    mumbai new york paris mumbai   
temperature                                                                 
28                NaN  1/3/2017       NaN       NaN     12.0   NaN    NaN   
32                NaN  1/1/2017       NaN       NaN      6.0   NaN    NaN   
33                NaN  1/4/2017       NaN       NaN      7.0   NaN    NaN   
36                NaN  1/2/2017       NaN       NaN      7.0   NaN    NaN   
42                NaN       NaN  1/4/2017       NaN      NaN  10.0    NaN   
45                NaN       NaN  1/1/2017       NaN      NaN  20.0    NaN   
50                NaN       NaN  1/2/2017       NaN      NaN  13.0    NaN   
54                NaN       NaN  1/3/2017       NaN      NaN   8.0    NaN   
85           1/2/2017       NaN       NaN      12.0      NaN   NaN    Fog   
87           1/3/2017       NaN       NaN      15.0      NaN   NaN    Fog   
90           1/1/2017       NaN       NaN       5.0      NaN   NaN  Sunny   
92           1/4/2017       NaN       NaN       5.0      NaN   NaN   Rain   

                              
city        new york   paris  
temperature                   
28              Snow     NaN  
32              Rain     NaN  
33             Sunny     NaN  
36             Sunny     NaN  
42               NaN  Cloudy  
45               NaN   Sunny  
50               NaN  Cloudy  
54               NaN  Cloudy  
85               NaN     NaN  
87               NaN     NaN  
90               NaN     NaN  
92               NaN     NaN

In [20]:
df.pivot_table(index='day',columns='city',aggfunc='sum')

event                  temperature                windspeed  \
city     mumbai new york   paris      mumbai new york paris    mumbai   
day                                                                     
1/1/2017  Sunny     Rain   Sunny          90       32    45         5   
1/2/2017    Fog    Sunny  Cloudy          85       36    50        12   
1/3/2017    Fog     Snow  Cloudy          87       28    54        15   
1/4/2017   Rain    Sunny  Cloudy          92       33    42         5   

                         
city     new york paris  
day                      
1/1/2017        6    20  
1/2/2017        7    13  
1/3/2017       12     8  
1/4/2017        7    10

In [21]:
df1 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['a','b','c'])
df1

a  b  c
0  1  2  3
1  4  5  6

In [22]:
df2 = pd.DataFrame([[10,2,30],[40,50,60]],columns=['a','b','d'])
df2

a   b   d
0  10   2  30
1  40  50  60

In [25]:
df3 = pd.concat([df1,df2],ignore_index=True,join = 'inner')
df3

a   b
0   1   2
1   4   5
2  10   2
3  40  50

In [28]:
df3 = pd.concat([df1,df2],axis=1,ignore_index=True)
df3

0  1  2   3   4   5
0  1  2  3  10   2  30
1  4  5  6  40  50  60

In [35]:
pd.merge(df1,df2,on='b',how = 'outer')

a_x   b    c   a_y     d
0  1.0   2  3.0  10.0  30.0
1  4.0   5  6.0   NaN   NaN
2  NaN  50  NaN  40.0  60.0